import { Response } from 'express';
import { dbClient } from '../repositories/dbClient';
import { AuthRequest } from '../middleware/authMiddleware';
import { Article, Quiz } from '../types';

const ARTICLES: Article[] = [
  {
    id: 'art-footprint',
    title: 'Understanding Carbon Footprints: The Basics',
    summary: 'What is a carbon footprint, why does it matter, and how does human activity drive emissions?',
    content: 'A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. Globally, the average carbon footprint is close to 4.7 tons per person annually. However, to avoid a 2°C rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.\n\nSmall changes in your daily routine—like reducing meat intake, taking public transit, or line-drying clothes—make a massive cumulative difference. Understanding where your emissions originate is the first step toward effective climate action.',
    category: 'General Climate Science',
    readTimeMinutes: 4,
    sdgAlignments: ['SDG 13']
  },
  {
    id: 'art-energy',
    title: 'Affordable Clean Energy at Home',
    summary: 'Practical tips to reduce electricity consumption and transition to renewable sources.',
    content: 'Our homes contribute a significant portion of our carbon footprints through electricity and heating fuels. In regions reliant on coal or gas generation, every kilowatt-hour (kWh) consumed releases approximately 0.4 kg of CO2. By setting air conditioners to 24°C, switching to LED bulbs, and unplugging idle chargers, you save energy and money (SDG 7).\n\nFor long-term impact, transitioning to solar water heaters, purchasing green energy tariffs, or installing rooftop photovoltaic panels can reduce home energy emissions to near zero.',
    category: 'Home Energy Efficiency',
    readTimeMinutes: 5,
    sdgAlignments: ['SDG 7', 'SDG 13']
  },
  {
    id: 'art-waste',
    title: 'Zero-Waste Habits: Methane & Plastics Solutions',
    summary: 'Learn how food waste and plastic consumption impact landfills and release potent greenhouse gases.',
    content: 'Waste is not just an aesthetic issue; it is a critical climate driver. When organic food waste decays in oxygen-deprived landfills, it releases methane (CH4), a greenhouse gas 25 times more potent than carbon dioxide (SDG 12). Reducing food waste and composting kitchen scraps keeps organics out of landfills.\n\nPlastics, being petrochemical products, release carbon during raw extraction, manufacturing, and incineration. Adopting reusable water bottles, recycling metal and glass, and reducing packaging purchases significantly lower carbon footprints.',
    category: 'Waste & Circular Economy',
    readTimeMinutes: 5,
    sdgAlignments: ['SDG 12']
  }
];

const QUIZZES: Quiz[] = [
  {
    id: 'quiz-basics',
    title: 'Climate Action & Carbon Basics',
    description: 'Test your understanding of carbon emissions, tree absorption rates, and UN SDGs!',
    pointsReward: 50,
    sdgAlignments: ['SDG 13'],
    questions: [
      {
        id: 'q1',
        question: 'Which of the following gases is the primary contributor to global greenhouse warming?',
        options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide (CO2)', 'Argon'],
        correctOptionIndex: 2,
        explanation: 'Carbon Dioxide is the main driver of global warming, releasing during fossil fuel combustion, deforestation, and industrial processes.'
      },
      {
        id: 'q2',
        question: 'Approximately how much CO2 does a single mature tree absorb per year?',
        options: ['5 kg', '22 kg', '100 kg', '500 kg'],
        correctOptionIndex: 1,
        explanation: 'A mature tree absorbs approximately 22 kg (48 lbs) of carbon dioxide from the atmosphere annually.'
      },
      {
        id: 'q3',
        question: 'What is the standard target temperature setting for Air Conditioners to optimize energy saving?',
        options: ['16°C', '20°C', '24°C', '28°C'],
        correctOptionIndex: 2,
        explanation: 'Setting your AC thermostat to 24°C (75°F) or higher offers the best balance of indoor comfort and electricity conservation (SDG 7).'
      },
      {
        id: 'q4',
        question: 'Which sector is responsible for the largest portion of greenhouse gas emissions globally?',
        options: ['Electricity & Heat Production', 'Agriculture', 'Transportation', 'Residential Buildings'],
        correctOptionIndex: 0,
        explanation: 'Electricity and heat production contributes about 25% of global greenhouse emissions, followed closely by agriculture/forestry and transport.'
      },
      {
        id: 'q5',
        question: 'Which diet type is associated with the absolute lowest daily carbon footprint?',
        options: ['Heavy Meat Diet', 'Mixed Diet', 'Vegetarian Diet', 'Vegan Diet'],
        correctOptionIndex: 3,
        explanation: 'A vegan (completely plant-based) diet is the most climate-friendly, emitting around 1.5 kg CO2 daily compared to 4.5 kg CO2 for a meat-heavy diet (SDG 12).'
      }
    ]
  }
];

export class EducationController {
  public static async getArticles(req: AuthRequest, res: Response) {
    try {
      const userId = req.user?.id;
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' });
      }

      const readProgress = await dbClient.getReadProgress(userId);
      const articlesWithProgress = ARTICLES.map(art => ({
        ...art,
        read: readProgress.some(rp => rp.articleId === art.id)
      }));

      return res.status(200).json({ articles: articlesWithProgress });
    } catch (err: any) {
      console.error('Get Articles Error:', err);
      return res.status(500).json({ error: 'Failed to retrieve educational articles.' });
    }
  }

  public static async logArticleRead(req: AuthRequest, res: Response) {
    try {
      const userId = req.user?.id;
      const { id } = req.params; // articleId

      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' });
      }

      const article = ARTICLES.find(a => a.id === id);
      if (!article) {
        return res.status(404).json({ error: 'Article not found' });
      }

      await dbClient.saveReadProgress(userId, id, new Date().toISOString());

      // Reward minor points for reading (e.g. 15 points)
      const user = await dbClient.findUserById(userId);
      let rewards = null;
      if (user) {
        // Only reward points if not already read
        const existingProgress = await dbClient.getReadProgress(userId);
        const alreadyReadCount = existingProgress.filter(rp => rp.articleId === id).length;
        if (alreadyReadCount <= 1) { // 1 because we just inserted it
          const newPoints = user.points + 15;
          const newLevel = Math.max(1, Math.floor(newPoints / 500) + 1);
          await dbClient.updateUserStats(userId, newPoints, newLevel, user.streakDays, user.lastActiveDate);
          rewards = { pointsEarned: 15, totalPoints: newPoints, level: newLevel };
        }
      }

      return res.status(200).json({ message: 'Article marked as read', rewards });
    } catch (err: any) {
      console.error('Log Article Read Error:', err);
      return res.status(500).json({ error: 'Failed to log article read progress.' });
    }
  }

  public static async getQuizzes(req: AuthRequest, res: Response) {
    try {
      const userId = req.user?.id;
      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' });
      }

      const quizProgress = await dbClient.getQuizProgress(userId);
      const quizzesWithProgress = QUIZZES.map(quiz => {
        const prog = quizProgress.find(qp => qp.quizId === quiz.id);
        return {
          ...quiz,
          completed: !!prog,
          score: prog ? prog.score : null
        };
      });

      return res.status(200).json({ quizzes: quizzesWithProgress });
    } catch (err: any) {
      console.error('Get Quizzes Error:', err);
      return res.status(500).json({ error: 'Failed to retrieve quizzes.' });
    }
  }

  public static async submitQuizScore(req: AuthRequest, res: Response) {
    try {
      const userId = req.user?.id;
      const { id } = req.params; // quizId
      const { score } = req.body; // number of correct answers (0 to 5)

      if (!userId) {
        return res.status(401).json({ error: 'Unauthorized' });
      }

      const quiz = QUIZZES.find(q => q.id === id);
      if (!quiz) {
        return res.status(404).json({ error: 'Quiz not found' });
      }

      const maxScore = quiz.questions.length;
      if (score < 0 || score > maxScore) {
        return res.status(400).json({ error: `Score must be between 0 and ${maxScore}` });
      }

      const prevProgress = await dbClient.getQuizProgress(userId);
      const alreadyCompleted = prevProgress.some(qp => qp.quizId === id);

      // Save score
      await dbClient.saveQuizProgress(userId, id, score, new Date().toISOString());

      let pointsEarned = 0;
      let totalPoints = 0;
      let newLevel = 1;
      let rewards = null;

      // Only reward points if this is the first time completing the quiz
      if (!alreadyCompleted && score >= 3) { // Requires passing score (>=60%)
        pointsEarned = quiz.pointsReward;
        const user = await dbClient.findUserById(userId);
        if (user) {
          totalPoints = user.points + pointsEarned;
          newLevel = Math.max(1, Math.floor(totalPoints / 500) + 1);
          await dbClient.updateUserStats(userId, totalPoints, newLevel, user.streakDays, user.lastActiveDate);
          rewards = { pointsEarned, totalPoints, level: newLevel };
        }
      }

      return res.status(200).json({
        message: score >= 3 ? 'Quiz passed!' : 'Quiz completed. Passing score is 3 or more.',
        score,
        maxScore,
        passed: score >= 3,
        rewards
      });
    } catch (err: any) {
      console.error('Submit Quiz Error:', err);
      return res.status(500).json({ error: 'Failed to submit quiz score.' });
    }
  }
}
export default EducationController;
